server:
  port: 8889
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8890/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true