server:
  port: 8901
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hph1234/springcloud-config.git
          username: hupohua
          clone-on-start: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/,http://localhost:8890/eureka/